#!/bin/bash
docker container cp $(docker ps -l --format "\nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n" | grep -i NAMES | cut -f2):/go/src/github.com/gilgameshskytrooper/prometheusweb/prometheusweb .
docker container cp $(docker ps -l --format "\nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n" | grep -i NAMES | cut -f2):/etc/ssl/certs/ca-certificates.crt .
rm -f $(docker ps -l --format $FORMAT | awk 'NR==2{print $2}')
