#!/bin/bash
docker container cp $(docker ps -l --format "\nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n" | grep -i NAMES | cut -f2):/etc/ssl/certs/ca-certificates.crt ca-certificates.crt
docker container cp $(docker ps -l --format "\nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n" | grep -i NAMES | cut -f2):/prometheus/prometheus prometheus
docker rm -f $(docker ps -l --format $FORMAT | awk 'NR==2{print $2}')
